// Generated by https://quicktype.io

export interface Address {
    id: number;
    Numero: string;
    Nombre: string;
    Apellido: string;
    Nit: string;
    Direccion: string;
    Indicacion: string;
    Tienda: string;
    Id_usuario: string;
    Pais: string;
    Departamento: string;
    Ciudad: string;
    Municipio: string;
    email: string;
    Link_tienda: string;
    created_at: string;
    updated_at: string;
}


